# Generated by Django 4.2.3 on 2024-01-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='ams.class'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_field',
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.course'),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='ams.course'),
        ),
        migrations.AddField(
            model_name='lab',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='ams.faculty'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='ams.course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='ams.faculty'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='ams.class'),
        ),
    ]
