# Generated by Django 4.2.3 on 2024-01-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0008_alter_class_incharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="head",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="head",
                to="ams.faculty",
            ),
        ),
    ]
