# Generated by Django 4.2.3 on 2024-01-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0009_alter_course_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableslot",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ams.batch",
            ),
        ),
    ]
