# Generated by Django 4.2.3 on 2024-02-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0011_remove_userprofile_is_br_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="ams.class",
            ),
        ),
    ]
