# Generated by Django 4.2.3 on 2024-02-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0012_alter_student_class_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ams.timetableslot",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ams.timetableslot",
            ),
        ),
    ]
