# Generated by Django 4.2.3 on 2024-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ams", "0004_remove_lab_course_remove_lab_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labattendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lecattendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
    ]
