# Generated by Django 4.2.3 on 2024-01-26 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ams", "0006_alter_course_head_alter_department_hod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="hod",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod",
                to="ams.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty",
                to="ams.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="ams.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
